### ISSUE TITLE
Could you kindly provide the covariance matrix (C = XX^T) for each task in GLUE, or any relevant source code?

### ISSUE THREAD

**Issue by juyongjiang** [iboing/CorDA#1]
@iboing @xiaojieli0903 Dear Authors,

Thank you for your excellent work! I am replicating the experimental results of CorDA in instruction-previewed adaptation mode on the GLUE benchmark using RoBERTa_base.

As outlined in Appendix A.2 GLUE Benchmark of your paper, the implementation details for the covariance matrix collection of CorDA are as follows:

> "For covariance matrix collection of CorDA, we concatenate the representative content of each training sample to form a text sequence. From this sequence, 256 text segments, each containing 256 tokens, are randomly sampled. The selected content for each task is as follows: MRPC, RTE, and STS-B using “sentence1”, CoLA and SST-2 using “sentence”, and QNLI using “question”."

To ensure consistency and avoid performance discrepancies, could you kindly provide the covariance matrix ( C = XX^T ) for each task? Alternatively, if available, could you share any relevant source code used to generate the task's data-driven covariance matrix?

Thank you very much for your assistance. : )

Best Regards,
John

**Comment by iboing** [comment]
Hi John, we collect covariance matrices from a mixed data of all the tasks. @xiaojieli0903  has resolved this issue offline, so I close it. Please let us know if you have any further questions.

**Comment by juyongjiang** [comment]
Yeah, @xiaojieli0903 has solved my question. I appreciate your help! : )
